name: Android CI/CD

on:
  push:
    branches:
      - '**'  # Trigger on all branches
  pull_request:
    branches:
      - '**'  # Trigger for pull requests on all branches

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    # Checkout repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Set up JDK
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    # Cache Gradle dependencies
    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    # Build and run unit tests
    - name: Build and Run Unit Tests
      run: ./gradlew build --no-daemon

    # Publish APK to GitHub Releases only on main branch
    - name: Publish to GitHub Releases
      if: github.ref == 'refs/heads/main'
      uses: ncipollo/release-action@v1
      with:
        tag: v${{ github.run_number }}
        release_name: "Release ${{ github.run_number }}"
        draft: false
        prerelease: false
        artifacts: app/build/outputs/apk/debug/app-debug.apk
        token: ${{ secrets.GITHUB_TOKEN }}
